FROM python:3.11-slim
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY src/ /app/src/
COPY models/ /app/models/
WORKDIR /app/src
EXPOSE 8010
CMD ["uvicorn", "tfidf_api:app", "--host", "0.0.0.0", "--port", "8010"]
